
all: libs examples rsdft_util

libs:
	cd src; make

examples:
	cd example; make

rsdft_util:
	cd rsdft_utility; make

clean:
	cd src; make clean
	cd example; make clean
	cd rsdft_utility; make clean

